### ISSUE TITLE
Error for assembly Microsoft.Office.Uc.

### ISSUE THREAD

**Issue by umaknow-charles** [ankitbko/SkypeForBusinessBot#1]
I get this error while running the LyncBot.Console.exe

Could not load file or assembly 'Microsoft.Office.Uc, Version=15.0.4603.1000, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.

**Comment by ankitbko** [comment]
Fixed it. In properties of Microsoft.Office.Uc "Embed Interos Types" was set to True which made "Copy Local" to false. Just changing it will work. I have pushed the changes.

**Comment by virendrak** [comment]
@ankitbko , this [change](https://github.com/ankitbko/SkypeForBusinessBot/issues/1#issuecomment-271768496) is also working fine. Thanks for your help.
