### ISSUE TITLE
Getting Exception: StackExchange.Redis.RedisConnectionException

### ISSUE THREAD

**Issue by virendrak** [ankitbko/SkypeForBusinessBot#2]
I am getting this error - Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(S); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING.

Please suggest me what I am doing wrong.

Thanks,
Viren

**Comment by ankitbko** [comment]
I pushed the change. Can you check please?

**Comment by virendrak** [comment]
Same error again..

> Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(S); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING

is it any environment related issue? I have these thing insatlled on my machine. VS 2015, Bot Frame-Work, and Lync Client (lyncentry.exe)

**Comment by ankitbko** [comment]
Did you pull the latest from git? I just commented the RedisStore injection. Can you check in `Program.cs` whether `InMemoryStore` is being used or not?

**Comment by virendrak** [comment]
Yes, I have taken latest Program.cs

`var builder = new ContainerBuilder();

            #region Redis

            //RedisStoreOptions redisOptions = new RedisStoreOptions()
            //{
            //    Configuration = "localhost"
            //};

            //builder.Register(c => new RedisStore(redisOptions))
            //   .As<RedisStore>()
            //   .SingleInstance();

            //builder.Register(c => new CachingBotDataStore(c.Resolve<RedisStore>(),
            //                                              CachingBotDataStoreConsistencyPolicy.ETagBasedConsistency))
            //    .As<IBotDataStore<BotData>>()
            //    .AsSelf()
            //    .InstancePerLifetimeScope();
            #endregion

            #region InMemory
            builder.RegisterType<InMemoryDataStore>()
                .AsSelf()
                .SingleInstance();

            builder.Register(c => new CachingBotDataStore(c.Resolve<InMemoryDataStore>(),
                                                          CachingBotDataStoreConsistencyPolicy.ETagBasedConsistency))
                .As<IBotDataStore<BotData>>()
                .AsSelf()
                .InstancePerLifetimeScope();

            #endregion

            List<string> managerList = GetManagerList();

            builder.Register(c => new ManagerScorable(c.Resolve<IBotToUser>(), managerList))
                .Keyed<ManagerScorable>(FiberModule.Key_DoNotSerialize)
                .As<IScorable<IActivity, double>>()
                .InstancePerLifetimeScope();

            builder.Update(Conversation.Container);`

**Comment by virendrak** [comment]
![image](https://cloud.githubusercontent.com/assets/10959600/21859283/09cb280e-d852-11e6-917d-bd9fbd54a79a.png)

**Comment by ankitbko** [comment]
I had commented `RedisStore` and used `InMemoryStore`. In no other place is Redis used. It may be due to old dll's. Can you try clearing bin and obj folder and build again.

**Comment by virendrak** [comment]
Thank you so much, now it's working fine.  I have few more doubts, will share details in next message.

Thanks,
Viren

**Comment by ankitbko** [comment]
Great. The reason was that since the bot will not be talking to Microsoft Bot Connector in any way, we would need to store bot's context somewhere our-self. I had used locally running instance of Redis. Now I have commented out `RedisStore` and used `InMemoryStore`. To use RedisStore uncomment the 'region' in `Program.cs` and comment InMemory 'region'.
