### ISSUE TITLE
SkypeForBusinessBot is responding only once for a Intent

### ISSUE THREAD

**Issue by virendrak** [ankitbko/SkypeForBusinessBot#3]
In **SkypeForBusinessBot**  project, when I ran it normally on my system, I noticed it’s giving response only once for every intent, but it is not responding after that for same intent.

**Example:** 
_Intent - Hello_
> Me - Hi
> Bot - Give Expected Reply
> Me - Hello
> Bot - No Response
> 
_Intent - Appreciate_
> Me - Great
> Bot - Gives Expected Response
> Me - Nice
> Bot - No Response

**Comment by ankitbko** [comment]
This is on purpose. I do not want to respond "Hello" many times to my colleagues. I had rather respond once and be quite next time.
`await context.PostOnlyOnceAsync(Responses.HiGreetingsResponse(name), nameof(HiGreetings));`
I have written an extension method for this, if you don't want this behavior you can use `context.PostAsync` instead.

**Comment by virendrak** [comment]
Thanks for the clarification and help!
